const dummyVideoData = [
  // Marques Brownlee (Channel 1)
  {
    video_id: "mkbhd_001",
    channel_id: 1,
    title: "iPhone 16 Pro Max - Worth the Upgrade?",
    uploadedAt: "2024-01-12T10:30:00Z",
    currentViewCount: 45000,
    predictedClassification: "viral",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "mkbhd_002",
    channel_id: 1,
    title: "Quick Tech News Update",
    uploadedAt: "2024-01-12T16:15:00Z",
    currentViewCount: 12000,
    predictedClassification: "average",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "mkbhd_003",
    channel_id: 1,
    title: "Tesla Cybertruck Final Review",
    uploadedAt: "2024-01-10T14:30:00Z",
    currentViewCount: 2100000,
    predictedClassification: "viral",
    actualClassification: "viral",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "mkbhd_004",
    channel_id: 1,
    title: "MacBook Air M3 vs M2 Comparison",
    uploadedAt: "2024-01-09T11:00:00Z",
    currentViewCount: 850000,
    predictedClassification: "viral",
    actualClassification: "average",
    wasCorrect: 0,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "mkbhd_005",
    channel_id: 1,
    title: "Why I Don't Use Wireless Charging",
    uploadedAt: "2024-01-08T09:45:00Z",
    currentViewCount: 45000,
    predictedClassification: "average",
    actualClassification: "average",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },

  // Linus Tech Tips (Channel 2)
  {
    video_id: "ltt_001",
    channel_id: 2,
    title: "Building a $10,000 Gaming PC",
    uploadedAt: "2024-01-12T12:00:00Z",
    currentViewCount: 180000,
    predictedClassification: "viral",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "ltt_002",
    channel_id: 2,
    title: "WAN Show Clips - CPU Market Drama",
    uploadedAt: "2024-01-12T18:30:00Z",
    currentViewCount: 25000,
    predictedClassification: "average",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "ltt_003",
    channel_id: 2,
    title: "RTX 4090 vs RTX 4080 - Which to Buy?",
    uploadedAt: "2024-01-10T15:45:00Z",
    currentViewCount: 1200000,
    predictedClassification: "viral",
    actualClassification: "viral",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "ltt_004",
    channel_id: 2,
    title: "Server Room Tour 2024",
    uploadedAt: "2024-01-09T13:20:00Z",
    currentViewCount: 95000,
    predictedClassification: "average",
    actualClassification: "underperforming",
    wasCorrect: 0,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "ltt_005",
    channel_id: 2,
    title: "Why Intel is in Trouble",
    uploadedAt: "2024-01-08T16:10:00Z",
    currentViewCount: 650000,
    predictedClassification: "average",
    actualClassification: "average",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },

  // Dave Lee (Channel 3)
  {
    video_id: "dave2d_001",
    channel_id: 3,
    title: "Framework Laptop 16 - Modular Gaming?",
    uploadedAt: "2024-01-12T14:20:00Z",
    currentViewCount: 68000,
    predictedClassification: "viral",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "dave2d_002",
    channel_id: 3,
    title: "Best Budget Laptop 2024",
    uploadedAt: "2024-01-12T20:15:00Z",
    currentViewCount: 15000,
    predictedClassification: "average",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "dave2d_003",
    channel_id: 3,
    title: "M3 MacBook Pro Real World Test",
    uploadedAt: "2024-01-10T11:30:00Z",
    currentViewCount: 890000,
    predictedClassification: "viral",
    actualClassification: "viral",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "dave2d_004",
    channel_id: 3,
    title: "Razer Blade 18 Review",
    uploadedAt: "2024-01-09T15:45:00Z",
    currentViewCount: 120000,
    predictedClassification: "average",
    actualClassification: "average",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "dave2d_005",
    channel_id: 3,
    title: "Why I Still Use Windows",
    uploadedAt: "2024-01-08T13:00:00Z",
    currentViewCount: 45000,
    predictedClassification: "underperforming",
    actualClassification: "underperforming",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },

  // Mrwhosetheboss (Channel 4)
  {
    video_id: "arun_001",
    channel_id: 4,
    title: "Samsung Galaxy S24 Ultra vs iPhone 15 Pro Max",
    uploadedAt: "2024-01-12T13:45:00Z",
    currentViewCount: 250000,
    predictedClassification: "viral",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "arun_002",
    channel_id: 4,
    title: "Tech News You Missed This Week",
    uploadedAt: "2024-01-12T19:00:00Z",
    currentViewCount: 35000,
    predictedClassification: "average",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "arun_003",
    channel_id: 4,
    title: "The Smartphone Awards 2023!",
    uploadedAt: "2024-01-10T16:30:00Z",
    currentViewCount: 3200000,
    predictedClassification: "viral",
    actualClassification: "viral",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "arun_004",
    channel_id: 4,
    title: "Nothing Phone 2a Review",
    uploadedAt: "2024-01-09T12:15:00Z",
    currentViewCount: 750000,
    predictedClassification: "viral",
    actualClassification: "average",
    wasCorrect: 0,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "arun_005",
    channel_id: 4,
    title: "My Home Office Setup 2024",
    uploadedAt: "2024-01-08T14:20:00Z",
    currentViewCount: 180000,
    predictedClassification: "average",
    actualClassification: "average",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },

  // ColdFusion (Channel 5)
  {
    video_id: "coldfusion_001",
    channel_id: 5,
    title: "The AI Revolution: What's Really Happening",
    uploadedAt: "2024-01-12T15:30:00Z",
    currentViewCount: 95000,
    predictedClassification: "viral",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "coldfusion_002",
    channel_id: 5,
    title: "Quick Update on Channel Direction",
    uploadedAt: "2024-01-12T21:45:00Z",
    currentViewCount: 8000,
    predictedClassification: "average",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "coldfusion_003",
    channel_id: 5,
    title: "The Rise and Fall of BlackBerry",
    uploadedAt: "2024-01-10T12:00:00Z",
    currentViewCount: 1800000,
    predictedClassification: "viral",
    actualClassification: "viral",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "coldfusion_004",
    channel_id: 5,
    title: "Quantum Computing Explained Simply",
    uploadedAt: "2024-01-09T10:30:00Z",
    currentViewCount: 450000,
    predictedClassification: "average",
    actualClassification: "average",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "coldfusion_005",
    channel_id: 5,
    title: "Music Production with AI Tools",
    uploadedAt: "2024-01-08T17:15:00Z",
    currentViewCount: 25000,
    predictedClassification: "underperforming",
    actualClassification: "underperforming",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },

  // Engadget (Channel 6)
  {
    video_id: "engadget_001",
    channel_id: 6,
    title: "CES 2024: Best New Tech",
    uploadedAt: "2024-01-12T11:15:00Z",
    currentViewCount: 72000,
    predictedClassification: "viral",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "engadget_002",
    channel_id: 6,
    title: "Weekly Gadget Roundup",
    uploadedAt: "2024-01-12T17:30:00Z",
    currentViewCount: 18000,
    predictedClassification: "average",
    actualClassification: undefined,
    wasCorrect: 2,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "engadget_003",
    channel_id: 6,
    title: "Apple Vision Pro Hands-On",
    uploadedAt: "2024-01-10T13:45:00Z",
    currentViewCount: 920000,
    predictedClassification: "viral",
    actualClassification: "viral",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "engadget_004",
    channel_id: 6,
    title: "Steam Deck OLED vs Original",
    uploadedAt: "2024-01-09T14:20:00Z",
    currentViewCount: 180000,
    predictedClassification: "average",
    actualClassification: "average",
    wasCorrect: 1,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },
  {
    video_id: "engadget_005",
    channel_id: 6,
    title: "Smart Home Trends 2024",
    uploadedAt: "2024-01-08T12:30:00Z",
    currentViewCount: 35000,
    predictedClassification: "average",
    actualClassification: "underperforming",
    wasCorrect: 0,
    thumbnail: {
      url: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
      width: 320,
      height: 180,
    },
  },

  // ...existing code... (continue similar pattern for channels 7-15)
];

export default dummyVideoData;
