version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: youtube_predictor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main FastAPI application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/youtube_predictor
      - REDIS_URL=redis://redis:6379/0
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Celery worker for background tasks
  worker:
    build: .
    command: celery -A src.tasks.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/youtube_predictor
      - REDIS_URL=redis://redis:6379/0
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # MLflow tracking server
  mlflow:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://postgres:postgres@db:5432/youtube_predictor
    command: >
      bash -c "
        pip install mlflow psycopg2-binary &&
        mlflow server 
          --backend-store-uri postgresql://postgres:postgres@db:5432/youtube_predictor
          --default-artifact-root ./mlruns
          --host 0.0.0.0
          --port 5000
      "
    volumes:
      - mlflow_data:/mlflow
    depends_on:
      - db

  # Next.js Dashboard
  dashboard:
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_MLFLOW_URL=http://localhost:5000
    volumes:
      - ./dashboard/src:/app/src
      - ./dashboard/public:/app/public
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  mlflow_data: